In [2]:
import crystal2qmc as c2q
import imp
import numpy as np

In [7]:
imp.reload(c2q)
info, lat_parm, ions, basis, pseudo = c2q.read_gred()
eigsys = c2q.read_kred(info,basis)

(2304, 48, 48)
[0 0 0]
[1 0 0]
[0 1 0]
[1 1 0]
[0 0 1]
[1 0 1]
[0 1 1]
[1 1 1]


In [6]:
basis['nao_shell']

array([1, 3, 5, 7, 1, 1, 3, 3, 1, 3, 5, 7, 1, 1, 3, 3])

In [16]:
eigvecs = eigsys['eigvecs_real'][0]
eigvecs.shape[1]

48

In [31]:
pseudo['n_per_j'][0:6]

array([3, 1, 1, 1, 0, 0])

In [18]:
int(sum(basis['nao_shell']))/len(ions['positions'])

24

In [24]:
48*2*24

2304

In [25]:
eigvecs.shape

(96, 48)

In [27]:
ions['atom_nums']v

array([233, 231])

In [4]:
pseudo

{'exponents': array([ 1.21796059,  9.96302171,  1.86158567,  3.54546456,  3.28664249,
         1.95862616,  1.22544253,  5.71065133,  1.33931968,  2.48772664,
         2.12489462,  1.27124173]),
 'n_per_j': array([3, 1, 1, 1, 0, 0, 3, 1, 1, 1, 0, 0]),
 'prefactors': array([  5.        ,   6.08980295, -14.92625816,  73.75553709,
         68.03580909,  23.32540737,   3.        ,   3.67632759,
        -11.23828733,  57.88512249,  43.67871044,  17.97137628]),
 'r_exps': array([-1,  1,  0,  0,  0,  0, -1,  1,  0,  0,  0,  0])}

In [6]:
pseudo['exponents'].size

12

In [7]:
pseudo['n_per_j'].size

12